include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - analyzer:
        errors:
          invalid_annotation_target: ignore
    - avoid_print
    - prefer_single_quotes
    - require_trailing_commas
    - always_use_package_imports
    - prefer_const_declarations