name: budget_tracker
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.5.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  firebase_core: ^2.27.0
  firebase_crashlytics: ^3.4.18
  firebase_analytics: ^10.8.9
  logging: ^1.2.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  auto_route: ^7.9.1
  flutter_svg: ^2.0.10+1
  vibration: ^1.8.4
  local_auth: ^2.2.0
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3
  flutter_emoji: ^2.5.1
  shared_preferences: ^2.2.2
  fl_chart: ^0.66.2
  dio: ^5.4.2
  rive: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  auto_route_generator: ^7.3.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/svg/
    - assets/pig.riv
    - assets/empty.riv
    - assets/exploration.riv
    - assets/error_server.riv

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Black.ttf
        - asset: fonts/Nunito-Bold.ttf
        - asset: fonts/Nunito-ExtraBold.ttf
        - asset: fonts/Nunito-ExtraLight.ttf
        - asset: fonts/Nunito-Light.ttf
        - asset: fonts/Nunito-Medium.ttf
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-SemiBold.ttf
